--Exploring all object in database;
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--Exploring all columns in database table;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dim_customers';

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dim_products';

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='fact_sales';

--Dim Exploration
SELECT DISTINCT country FROM Gold.dim_customers;

SELECT DISTINCT gender FROM Gold.dim_customers;

SELECT DISTINCT category,subcategory,product_name FROM Gold.dim_products order by 1,2,3;

--Date exploration
SELECT MIN(order_date)first_date,MAX(order_date)last_Date,DATEDIFF(YEAR,MIN(order_date),MAX(order_date))range_in_year FROM Gold.fact_sales;

SELECT * FROM Gold.dim_customers where birthday in ((select MIN(birthday) from Gold.dim_customers)union(select MAX(birthday) from Gold.dim_customers));

--Measures--
--TOTAL SALES--
SELECT SUM(sales_amount) AS Total_sales FROM Gold.fact_sales;

--TOTAL ITEMS--
SELECT SUM(quantity) AS Total_items FROM Gold.fact_sales;

--AVG PRICE--
SELECT AVG(unit_price) AS Average_price FROM Gold.fact_sales;

--TOTAL ORDERS--
SELECT COUNT(DISTINCT order_number) FROM Gold.fact_sales;

--TOTAL PRODUCTS--
SELECT COUNT(*) FROM Gold.dim_products;

--TOTAL CUSTOMERS--
SELECT COUNT(*) FROM Gold.dim_customers;

--TOTAL CUSTOMER PLACED ORDER 
SELECT COUNT (DISTINCT customer_key) FROM Gold.fact_sales;

--ALL TOGETHER 
SELECT 'Total_sales' AS Measure_name,SUM(sales_amount) AS Value FROM Gold.fact_sales
UNION ALL
SELECT 'Total_quantity' AS Measure_name,SUM(quantity) AS Value FROM Gold.fact_sales
UNION ALL
SELECT 'Average_price' AS Measure_name,AVG(unit_price) AS Value FROM Gold.fact_sales
UNION ALL
SELECT 'Total_orders' AS Measure_name,COUNT(DISTINCT order_number)AS Value FROM Gold.fact_sales
UNION ALL
SELECT 'Total_products' AS Measure_name,COUNT(*)AS Value FROM Gold.dim_products
UNION ALL
SELECT 'Total_customers' AS Measure_name,COUNT(*)AS Value FROM Gold.dim_customers;

--Magnitude
--Total customers by country
SELECT country,COUNT(*)AS No_of_cust FROM Gold.dim_customers GROUP BY country ORDER BY No_of_cust DESC;
--Total customers by gender
SELECT gender,COUNT(*)AS No_of_cust FROM Gold.dim_customers GROUP BY gender ORDER BY No_of_cust DESC;
--Total products by category
SELECT category,COUNT(*)AS No_of_prod FROM Gold.dim_products GROUP BY category ORDER BY No_of_prod DESC;
--Avg cost in each category
SELECT category,AVG(product_cost)AS Avg_cost FROM Gold.dim_products GROUP BY category ORDER BY Avg_cost DESC;
--Total revenue generated by each category
SELECT dp.category,SUM(fs.sales_amount)AS Total_revenue FROM Gold.fact_sales fs LEFT JOIN Gold.dim_products dp ON fs.product_key=dp.product_key GROUP BY dp.category ORDER BY Total_revenue DESC;

-- What is the total revenue generated by each customer?
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?

SELECT
c.country,
SUM(f.quantity) AS total_sold_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_quantity DESC

--Ranking Analysis
--Top 5 product with highest revenue
SELECT TOP 5 p.product_name,SUM(f.sales_amount)AS Revenue,ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC)AS RANKING FROM Gold.fact_sales f LEFT JOIN Gold.dim_products p 
ON p.product_key=f.product_key GROUP BY product_name

--Worst 5 performing product
SELECT * FROM(SELECT p.product_name,SUM(f.sales_amount)AS Revenue,ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount))AS RANKING FROM Gold.fact_sales f LEFT JOIN Gold.dim_products p 
ON p.product_key=f.product_key GROUP BY product_name)t WHERE RANKING<6;

--Top 10 and lowest 3
SELECT TOP 10 p.product_name,SUM(f.sales_amount)AS Revenue,ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC)AS RANKING FROM Gold.fact_sales f LEFT JOIN Gold.dim_products p 
ON p.product_key=f.product_key GROUP BY product_name;

SELECT TOP 3 p.product_name,COUNT(DISTINCT order_number) AS Total_orders,ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount))AS RANKING FROM Gold.fact_sales f LEFT JOIN Gold.dim_products p 
ON p.product_key=f.product_key GROUP BY product_name;

--Change over time
SELECT DATETRUNC(YEAR,order_date) as [year over year],sum(sales_amount) AS Sales_amount, COUNT(DISTINCT customer_key) as total_cust,sum(quantity) as total_quantity FROM Gold.fact_sales WHERE order_date is not null GROUP BY DATETRUNC(YEAR,order_date) ORDER BY [year over year];

--Cumulative analysis--
--total sales over month and running total of sales over time;
SELECT order_date,total_sales,sum(total_sales) OVER(ORDER BY order_date)runningtotal,avg(AVGPRICE) over (order by order_date) runningavg FROM(
SELECT DATETRUNC(MONTH,order_date)order_date,SUM(sales_amount)total_sales,AVG(unit_price)AVGPRICE FROM Gold.fact_sales WHERE order_date is not null GROUP BY DATETRUNC(MONTH,order_date))t;

--performance analysis
--Analyze performance of products by comparing their sales to avg sales performance of product to previous year sales
WITH yearly_product_sales AS(
SELECT YEAR(f.order_date) YEAR ,p.product_name,SUM(sales_amount)Totalsales FROM Gold.fact_sales f LEFT JOIN Gold.dim_products p ON p.product_key=f.product_key where order_date is not null group by year(f.order_date),p.product_name)
select YEAR,product_name,Totalsales,avg(Totalsales) over (partition by product_name),Totalsales-avg(Totalsales) over (partition by product_name) diff_avg,case when Totalsales-avg(Totalsales) over (partition by product_name) >0 then 'Above avg' else 'below avg' end avg_change,lag(Totalsales) over(partition by product_name order by year) py_sales ,Totalsales-lag(Totalsales) over(partition by product_name order by year) yoy_sales,case when Totalsales-lag(Totalsales) over(partition by product_name order by year) >0 then 'increasing' when Totalsales-lag(Totalsales) over(partition by product_name order by year)<0 then 'decreasing' else 'same' end pysales_change  from yearly_product_sales order by 2,1;


--With subquery
SELECT YEAR,product_name,Totalsales,avg(Totalsales) over(partition by product_name) as avgsales,Totalsales-avg(Totalsales) over(partition by product_name),lag(Totalsales) over (partition by product_name ORDER BY year),case when Totalsales-avg(Totalsales) over(partition by product_name) >0 then 'avgsale' else 'belowavg' end type from (SELECT YEAR(f.order_date) YEAR ,p.product_name,SUM(sales_amount)Totalsales FROM Gold.fact_sales f LEFT JOIN Gold.dim_products p ON p.product_key=f.product_key where order_date is not null group by year(f.order_date),p.product_name)t;

--part to whole analysis
--Category wise analysis 
SELECT 
p.category,
sum(s.sales_amount),
SUM(sum(s.sales_amount)) over() total_sales,
concat(round((cast(sum(s.sales_amount)as float)/SUM(sum(s.sales_amount))over())*100,2),'%') as percentage
FROM Gold.fact_sales s
left join 
Gold.dim_products p
on s.product_key=p.product_key 
group by p.category

--data segmentation
--Segment product into cost ranges and count how many product fall in each segment
select segment,count(*) totalproducts from(select product_name,product_cost,case when product_cost>0 and product_cost<=100 then 'below 100' when product_cost between 100 and 500 then '100-500' when product_cost between 501 and 1000 then '501-1000' else 'above 1000' end segment from Gold.dim_products)t group by segment order by totalproducts desc

--Segment customers
with customer_spending as (
SELECT c.customer_key,sum(s.sales_amount)total_sales,min(s.order_date)first_order,max(s.order_date) last_order,DATEDIFF(MONTH,min(s.order_date),max(s.order_date))lifespan,case when DATEDIFF(MONTH,min(s.order_date),max(s.order_date))>=12 and sum(s.sales_amount)>5000 then 'Vip' when DATEDIFF(MONTH,min(s.order_date),max(s.order_date))>=12 and sum(s.sales_amount)<=5000 then 'Regular' else 'New' end customer_segment from Gold.fact_sales s left join Gold.dim_customers c on c.customer_key=s.customer_key group by c.customer_key)
select customer_segment,count(*) total_cust from customer_spending group by customer_segment order by total_cust desc

/*

Customer Report

Purpose:
- This report consolidates key customer metrics and behaviors

Highlights:
1. Gathers essential fields such as names, ages, and transaction details.
2. Segments customers into categories (VIP, Regular, New) and age groups.
3. Aggregates customer-level metrics:
- total orders
- total sales
- total quantity purchased
- total products
- lifespan (in months)
4. Calculates valuable KPIs:
- recency (months since last order)
- average order value
- average monthly spend

*/

SELECT s.order_number,p.product_key,s.order_date,s.sales_amount,s.quantity,c.customer_key,c.customer_number,CONCAT(c.first_name,' ',c.last_name) full_name,CASE WHEN DATEDIFF(YEAR,birthday,GETDATE())>=18 and DATEDIFF(YEAR,birthday,GETDATE())<=30 then '18-30' when DATEDIFF(YEAR,birthday,GETDATE())>=31 and DATEDIFF(YEAR,birthday,GETDATE())<=40 then '31-40' else '40 above' end age_group  FROM Gold.fact_sales s left join Gold.dim_customers c  on c.customer_key=s.customer_key left join  Gold.dim_products p on p.product_key=s.product_key where s.order_date is not null;